version: "3.8"
services: 
  api: 
    build: ./server
    image: nguyen8a/dev-nalendar-api:v0
    container_name: api_container
    ports:
      - '8000:8000'

    # volumes:
    #   - ./server:/api
    #   - /api/node_modules


  app: 
    build: ./client/Dockerfile-dev
    image: nguyen8a/dev-nalendar-app:v0
    container_name: app_container
    ports:
      - '3000:3000'

      # volumes:
      #   - ./client:/app
      #   - /app/node_modules

    stdin_open: true
    tty: true

    # # docker-compose -f local-docker-compose.yml up
