version: "3.8"
services: 
  api: 
    image: nguyen8a/nalendar-api
    container_name: api_container
    ports:
      - '8000:8000'

  app: 
    image: nguyen8a/nalendar-app
    container_name: app_container
    ports:
      - '3000:80'

    stdin_open: true
    tty: true

    # # docker-compose -f local-docker-compose.yml up
